#!/bin/bash
if [[ $1 != text && $1 != merge ]]; then
    echo ERROR: unknown app: $1; exit 1
fi
case $2 in
    mac  )
        package=sublime_$1_build_$3_mac.zip
        file="Sublime ${1^}.app/Contents/MacOS/sublime_$1"
        ;;
    win  )
        package=sublime_$1_build_$3_x64.zip
        file=sublime_$1.exe
        ;;
    linux)
        package=sublime-$1-$3-1-x86_64.pkg.tar.xz
        file=opt/sublime_$1/sublime_$1
        ;;
    linux-arm64)
        package=sublime-$1-$3-1-aarch64.pkg.tar.xz
        file=opt/sublime_$1/sublime_$1
        ;;
    *    ) echo ERROR: unknown platform: $2; exit 2 ;;
esac

target=sublime_$1_$2_$3
if [[ -f $target ]]; then
    echo ERROR: $target already exists; exit 3
fi
# ST download links: https://www.sublimetext.com/download_thanks
# SM download links: https://www.sublimemerge.com/download_thanks

case $package in
    *.zip)
        # mount remote archive to a local path with FUSE (https://github.com/higlass/simple-httpfs)
        ps -C simple-httpfs || simple-httpfs --schema=https $HOME/fuse-mounts
        package=$HOME/fuse-mounts/download.sublimetext.com/$package..
        # wget --continue https://download.sublimetext.com/$package
        # unzip $package "$file"
        7zz e $package "$file"
        # 7-zip can extract file without archived file path (and show progress of extraction)
    ;;
    *    )
        wget --continue https://download.sublimetext.com/$package
        tar --strip-components=2 -xf $package "$file"
        # skipping file path in archive (opt/sublime_$1)
    ;;
esac
mv -v ${file##*/} $target
