#!/bin/bash
if [[ $1 != text && $1 != merge ]]; then
    echo unknow app: $1; exit 1
fi
case $2 in
    mac  )
        package=sublime_$1_build_$3_mac.zip
        file="Sublime ${1^}.app/Contents/MacOS/sublime_$1"
        ;;
    win  )
        package=sublime_$1_build_$3_x64.zip
        file=sublime_$1.exe
        ;;
    linux)
        package=sublime-$1-$3-1-x86_64.pkg.tar.xz
        file=opt/sublime_$1/sublime_$1
        ;;
    linux-arm64)
        package=sublime-$1-$3-1-aarch64.pkg.tar.xz
        file=opt/sublime_$1/sublime_$1
        ;;
    *    ) echo unknown platform: $2; exit 2 ;;
esac
if [[ ! -f $package ]]; then
    wget https://download.sublimetext.com/$package
	# direct link from https://www.sublimetext.com/download_thanks and https://www.sublimemerge.com/download_thanks
fi
case $package in
    *.zip) unzip -p $package "$file" > sublime_$1_$2_$3 ;;
    *    ) tar -Oxf $package "$file" > sublime_$1_$2_$3 ;;
esac
# mv -v "$file" sublime_$1_$2_$3
echo extracted file: sublime_$1_$2_$3
